name: produtor-consumidor

services:
  cliente-back:
    image: cliente-back:latest
    build:
      context: ./cliente
      dockerfile: Dockerfile
    environment:
      - URL_LANCHONETE=http://lanchonete-back:8080
    ports:
      - "8080:8080"

  lanchonete-back:
    image: lanchonete-back:latest
    build: 
      context: ./lanchonete
      dockerfile: Dockerfile
    ports:
      - "8081:8080"