name: produtor-consumidor

services:
  cliente-back:
    image: cliente-back:latest
    build:
      context: ./cliente
      dockerfile: Dockerfile
    environment:
      - URL_LANCHONETE=localhosot:8081
    ports:
      - "8080:8080"